name: Upload Android Release to Play Store
uses: r0adkll/upload-google-play@v1
on:
  push:
    branches:
      - main
with:
  serviceAccountJson: ${{ SERVICE_ACCOUNT_JSON }}
  packageName: com.popovich.kotlintipsdaily
  releaseFiles: app/build/outputs/bundle/release/*.aab
  track: production
  mappingFile: app/build/outputs/mapping/release/mapping.txt